In [4]:
# area variables (in square meters)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# Create list areas
areas = [hall,kit,liv,bed,bath]
areas

[11.25, 18.0, 20.0, 10.75, 9.5]

In [5]:
# area variables (in square meters)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# Adapt list areas
areas = ["hallway", hall,"kitchen", kit, "living room", liv, "bedroom", bed, "bathroom", bath]

# Print areas
areas

['hallway',
 11.25,
 'kitchen',
 18.0,
 'living room',
 20.0,
 'bedroom',
 10.75,
 'bathroom',
 9.5]

In [1]:
import numpy as np
m = np.array([2,4,5])
n = 3
print(m*n)

[ 6 12 15]


In [7]:
print(type(13 / 3))
print(type(13 // 3))

<class 'float'>
<class 'int'>


In [8]:
x = np.array([[1, 3, 8], [3, 2, 6]])
y = np.array([[6, 4, 2], [0, 5, 1]])
print(x-y)

[[-5 -1  6]
 [ 3 -3  5]]


In [9]:
x = ['n', 'z', 'v', 's', 't', 'h', 'o']
print(x[-7] + x[-5])

nv


In [10]:
x = ['n', 'z', 'v', 's', 't', 'h', 'o']
print(x[-4] + x[-6])

sz


In [11]:
x = ['n', 'z', 'v', 's', 't', 'h', 'o']
print(x[-2] + x[-5])

hv


In [14]:
# area variables (in square meters)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# house information as list of lists
house = [["hallway", hall],
         ["kitchen", kit],
         ["living room", liv],
         ["bedroom", bed],
         ["bathroom", bath],]

# Print out house
print(house)

# Print out the type of house
print(type(house))


[['hallway', 11.25], ['kitchen', 18.0], ['living room', 20.0], ['bedroom', 10.75], ['bathroom', 9.5]]
<class 'list'>


In [24]:
#0-indexing in a list
fam = ["liz",1.73,"emma",1.68,"mom",1.71,"dad",1.89]
print(fam[2])
print(fam[-2])


emma
dad


In [28]:
#0-indexing in a list [ inclusive : exclusive ]
fam = ["liz",1.73,"emma",1.68,"mom",1.71,"dad",1.89]
print(fam[2:4])
print(fam[4:]) # : without number means everything behing
print(fam[:4]) # blank infront : means 0 onwards
print(fam[:])  # sames as print(fam)


['emma', 1.68]
['mom', 1.71, 'dad', 1.89]
['liz', 1.73, 'emma', 1.68]
['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89]


In [32]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Print out second element from areas
print(areas[1])

# Print out last element from areas
print(areas[-1])

# Print out the area of the living room
print(areas[5])

11.25
9.5
20.0


In [34]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Sum of kitchen and bedroom area: eat_sleep_area
eat_sleep_area = (areas[3]+areas[-3])

# Print the variable eat_sleep_area
print(eat_sleep_area)

28.75


In [36]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Use slicing to create downstairs
downstairs = areas[0:6]

# Use slicing to create upstairs
upstairs = areas[-4:]

# Print out downstairs and upstairs
print(downstairs)
print(upstairs)

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0]
['bedroom', 10.75, 'bathroom', 9.5]


In [37]:
house[-1][1] #points to float bathroom area

9.5

In [2]:
fam = ["liz",1.73,"emma",1.68,"mom",1.71,"dad",1.89]
#change dad's height from 1.89 to 1.86
fam[7] = 1.86
fam

['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.86]

In [3]:
fam = ["liz",1.73,"emma",1.68,"mom",1.71,"dad",1.89]
#change liz's name and height together
fam[0:2] = ["lisa",1.74]
fam



['lisa', 1.74, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89]

In [14]:
fam = ["liz",1.73,"emma",1.68,"mom",1.71,"dad",1.89]
#adding and removing elements
fam_ext = fam + ["me", 1.79]
print(fam_ext)


['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89, 'me', 1.79]


In [15]:
#removing elements
del(fam[2])
fam

['liz', 1.73, 1.68, 'mom', 1.71, 'dad', 1.89]

In [21]:
x = ['a','b','c']
y = x 
y[1] = 'z'
print(y)
print(x)

['a', 'z', 'c']
['a', 'z', 'c']


In [24]:
x = ['a','b','c']
y = list(x) #use the list function to ascertain x
y = x[:] #slice the x out from y list with this code
y[1] = 'z' #now change elements in y 
print(y)
print(x) #x list is not affected.

['a', 'z', 'c']
['a', 'b', 'c']


In [7]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Correct the bathroom area
areas[-1] = 10.5

# Change "living room" to "chill zone"
areas[4] = 'chill zone'
print(areas)



['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5]


In [10]:
# Create the areas list and make some changes
areas = ["hallway", 11.25, "kitchen", 18.0, "chill zone", 20.0,
         "bedroom", 10.75, "bathroom", 10.50]

# Add poolhouse data to areas, new list is areas_1
areas_1 = areas + ['poolhouse', 24.5]
print(areas_1)

# Add garage data to areas_1, new list is areas_2
areas_2 = areas_1 + ['garage', 15.45]
print(areas_2)

['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'poolhouse', 24.5]
['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'poolhouse', 24.5, 'garage', 15.45]
