In [4]:
# area variables (in square meters)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# Create list areas
areas = [hall,kit,liv,bed,bath]
areas

[11.25, 18.0, 20.0, 10.75, 9.5]

In [5]:
# area variables (in square meters)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# Adapt list areas
areas = ["hallway", hall,"kitchen", kit, "living room", liv, "bedroom", bed, "bathroom", bath]

# Print areas
areas

['hallway',
 11.25,
 'kitchen',
 18.0,
 'living room',
 20.0,
 'bedroom',
 10.75,
 'bathroom',
 9.5]

In [1]:
import numpy as np
m = np.array([2,4,5])
n = 3
print(m*n)

[ 6 12 15]


In [7]:
print(type(13 / 3))
print(type(13 // 3))

<class 'float'>
<class 'int'>


In [8]:
x = np.array([[1, 3, 8], [3, 2, 6]])
y = np.array([[6, 4, 2], [0, 5, 1]])
print(x-y)

[[-5 -1  6]
 [ 3 -3  5]]


In [9]:
x = ['n', 'z', 'v', 's', 't', 'h', 'o']
print(x[-7] + x[-5])

nv


In [10]:
x = ['n', 'z', 'v', 's', 't', 'h', 'o']
print(x[-4] + x[-6])

sz


In [11]:
x = ['n', 'z', 'v', 's', 't', 'h', 'o']
print(x[-2] + x[-5])

hv


In [14]:
# area variables (in square meters)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# house information as list of lists
house = [["hallway", hall],
         ["kitchen", kit],
         ["living room", liv],
         ["bedroom", bed],
         ["bathroom", bath],]

# Print out house
print(house)

# Print out the type of house
print(type(house))


[['hallway', 11.25], ['kitchen', 18.0], ['living room', 20.0], ['bedroom', 10.75], ['bathroom', 9.5]]
<class 'list'>


In [24]:
#0-indexing in a list
fam = ["liz",1.73,"emma",1.68,"mom",1.71,"dad",1.89]
print(fam[2])
print(fam[-2])


emma
dad


In [28]:
#0-indexing in a list [ inclusive : exclusive ]
fam = ["liz",1.73,"emma",1.68,"mom",1.71,"dad",1.89]
print(fam[2:4])
print(fam[4:]) # : without number means everything behing
print(fam[:4]) # blank infront : means 0 onwards
print(fam[:])  # sames as print(fam)


['emma', 1.68]
['mom', 1.71, 'dad', 1.89]
['liz', 1.73, 'emma', 1.68]
['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89]
